### PR TITLE
Always email members added to organization

### PR DESCRIPTION
**Pull request by Hazelfire**
Fixes an issue with Guesstimate saying it says an email to invite members but doesn't.

### CODE REVIEW

**Comment by OAGr** [comment]
Hm... does the new user email say that they need to sign up? I'd want to check that first, before we decide to send this out. I could easily see it leading to as signup page or something confusing.

**Comment by Hazelfire** [comment]
This is one possible solution, although I haven't had the chance to test this. I'll do that now

**Comment by Hazelfire** [comment]
It doesn't lead to the signup page, it leads to the main page. The emails are now slightly different to ask one to log in vs sign up.

**Comment by OAGr** [comment]
I like that, nice fix.

**Pull request merged**
